import {
  HOME_SERVICE_CATALOG,
  SERVICE_PROFICIENCIES
} from "@illamhelp/shared-types";

export const FALLBACK_SERVICE_CATALOG = HOME_SERVICE_CATALOG;

export const PROFICIENCY_OPTIONS = SERVICE_PROFICIENCIES;
